name: CI/CD for Dockerized Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: |
          echo "${{ env.docker_password }}" | docker login -u "${{ env.docker_username }}" --password-stdin
        env:
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.docker_username }}/flasktest-app:latest
